eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: schoolManagementServer
server:
  port: 9091
spring:
  application:
    name: School-Management-Service
  datasource:
    username: hobject
    password: hobject
    url: jdbc:postgresql://localhost:5432/school
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

